-- SICC target schema for Supabase PostgreSQL.
-- Apply with `supabase db push` (or the SQL editor) only after reviewing it
-- against the destination project. No production data is included here.

create extension if not exists pgcrypto;
create extension if not exists vector with schema extensions;

create table if not exists public.operator_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  war_name text not null check (char_length(trim(war_name)) between 2 and 80),
  rank text not null check (char_length(trim(rank)) between 1 and 80),
  role text not null default 'operator' check (role in ('admin', 'operator')),
  invited_by uuid references public.operator_profiles(user_id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.operator_invites (
  id bigint generated by default as identity primary key,
  code_hash text not null unique,
  created_by uuid not null references public.operator_profiles(user_id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  used_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint invite_expiry_after_creation check (expires_at > created_at)
);

create table if not exists public.factions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  full_name text not null,
  nickname text,
  cpf text not null unique,
  birth_date date,
  mother_name text,
  city text,
  state text,
  status text not null default 'review' check (status in ('verified', 'review', 'attention')),
  notes text,
  faction_id bigint references public.factions(id) on delete set null,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  label text not null default 'Residencial',
  address text not null,
  city text,
  state text,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.approaches (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  occurred_at timestamptz not null,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  accuracy_meters integer,
  location_label text,
  notes text,
  operator_id uuid not null references auth.users(id) on delete restrict,
  operator_email text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.seized_objects (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  description text not null,
  quantity integer not null default 1 check (quantity > 0),
  seized_at timestamptz,
  location text,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.person_media (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  kind text not null check (kind in ('face', 'face_front', 'face_profile', 'tattoo')),
  object_key text not null unique,
  original_name text not null,
  content_type text not null check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
  byte_size integer not null check (byte_size > 0 and byte_size <= 5242880),
  sha256 text not null,
  face_embedding extensions.vector(128),
  face_embedding_model text,
  face_embedding_created_at timestamptz,
  description text,
  captured_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.qtc_alerts (
  id bigint generated by default as identity primary key,
  category_key text not null,
  category_label text not null,
  priority text not null check (priority in ('Baixa', 'Média', 'Alta', 'Extrema')),
  municipality text not null,
  municipality_state text not null check (char_length(municipality_state) = 2),
  neighborhood text not null,
  people_info text,
  vehicle_info text,
  description text not null,
  occurred_at timestamptz not null,
  location_link text,
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_by_name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_by_name text,
  resolved_at timestamptz
);

create table if not exists public.qtc_alert_media (
  id bigint generated by default as identity primary key,
  alert_id bigint not null references public.qtc_alerts(id) on delete cascade,
  object_key text not null unique,
  original_name text not null,
  content_type text not null check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
  byte_size integer not null check (byte_size > 0 and byte_size <= 2500000),
  sha256 text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  operator_id uuid references auth.users(id) on delete set null,
  operator_email text not null,
  action text not null,
  target_id bigint,
  query text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists people_full_name_idx on public.people using gin (to_tsvector('simple', full_name));
create index if not exists people_nickname_idx on public.people (nickname);
create index if not exists people_cpf_idx on public.people (cpf);
create index if not exists addresses_person_idx on public.addresses (person_id);
create index if not exists approaches_person_date_idx on public.approaches (person_id, occurred_at desc);
create index if not exists seized_objects_person_idx on public.seized_objects (person_id);
create index if not exists person_media_person_idx on public.person_media (person_id);
create index if not exists person_media_kind_idx on public.person_media (kind);
-- HNSW is optional at very small volumes but keeps the target scalable.
create index if not exists person_media_face_embedding_idx on public.person_media
  using hnsw (face_embedding extensions.vector_l2_ops) where face_embedding is not null;
create index if not exists qtc_alerts_created_idx on public.qtc_alerts (created_at desc);
create index if not exists qtc_alerts_category_idx on public.qtc_alerts (category_key);
create index if not exists qtc_alerts_municipality_idx on public.qtc_alerts (municipality);
create index if not exists qtc_alert_media_alert_idx on public.qtc_alert_media (alert_id);
create index if not exists audit_created_at_idx on public.audit_logs (created_at desc);

-- Keep updated_at server-controlled.
create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = timezone('utc', now()); return new; end;
$$;
drop trigger if exists people_set_updated_at on public.people;
create trigger people_set_updated_at before update on public.people
for each row execute function public.set_updated_at();
drop trigger if exists operator_profiles_set_updated_at on public.operator_profiles;
create trigger operator_profiles_set_updated_at before update on public.operator_profiles
for each row execute function public.set_updated_at();

-- Authorization helpers read server-owned profiles, never user-editable metadata.
create schema if not exists private;
create or replace function private.is_operator()
returns boolean language sql stable security definer set search_path = public, auth as $$
  select exists (select 1 from public.operator_profiles where user_id = (select auth.uid()));
$$;
create or replace function private.is_admin()
returns boolean language sql stable security definer set search_path = public, auth as $$
  select exists (select 1 from public.operator_profiles where user_id = (select auth.uid()) and role = 'admin');
$$;
revoke all on function private.is_operator() from public;
revoke all on function private.is_admin() from public;
grant execute on function private.is_operator() to authenticated;
grant execute on function private.is_admin() to authenticated;

-- Expose tables only to authenticated operators; RLS remains the authority.
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;

do $$ declare t text; begin
  foreach t in array array['operator_profiles','operator_invites','factions','people','addresses','approaches','seized_objects','person_media','qtc_alerts','qtc_alert_media','audit_logs'] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

create policy operator_profiles_select on public.operator_profiles for select to authenticated
  using (user_id = (select auth.uid()) or (select private.is_admin()));
create policy operator_profiles_insert on public.operator_profiles for insert to authenticated
  with check (user_id = (select auth.uid()) and role = 'operator');
create policy operator_profiles_update on public.operator_profiles for update to authenticated
  using (user_id = (select auth.uid()) or (select private.is_admin()))
  with check ((user_id = (select auth.uid()) and role = 'operator') or (select private.is_admin()));

create policy invites_select on public.operator_invites for select to authenticated
  using (created_by = (select auth.uid()) or (select private.is_admin()));
create policy invites_insert on public.operator_invites for insert to authenticated
  with check ((select private.is_operator()) and created_by = (select auth.uid()));

create policy factions_all on public.factions for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy people_all on public.people for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy addresses_all on public.addresses for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy approaches_all on public.approaches for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy seized_objects_all on public.seized_objects for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy person_media_all on public.person_media for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy qtc_alerts_all on public.qtc_alerts for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy qtc_alert_media_all on public.qtc_alert_media for all to authenticated
  using ((select private.is_operator())) with check ((select private.is_operator()));
create policy audit_logs_insert on public.audit_logs for insert to authenticated
  with check ((select private.is_operator()) and operator_id = (select auth.uid()));
create policy audit_logs_select on public.audit_logs for select to authenticated
  using ((select private.is_admin()) or operator_id = (select auth.uid()));

-- Intentionally no visual_hash/perceptual-hash column is carried forward.
-- The beta's 128-value face descriptor maps to pgvector. Search must remain in
-- a server/Edge Function, use an approved threshold, and require human review.
-- Images are stored in a private Supabase Storage bucket. PostgreSQL stores
-- object_key and metadata; the Edge Function must authorize and sign every read.
