-- One-time activation links for the first administrator. The raw token is
-- never stored and this table is intentionally inaccessible through the
-- browser-facing Data API.
create table if not exists public.bootstrap_invites (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  constraint bootstrap_invite_expiry_after_creation check (expires_at > created_at)
);

alter table public.bootstrap_invites enable row level security;
revoke all on table public.bootstrap_invites from anon, authenticated;
grant select, insert, update, delete on table public.bootstrap_invites to service_role;
grant usage, select on sequence public.bootstrap_invites_id_seq to service_role;
